function generateCode() {
  const editor = document.getElementById("editor");
  editor.value = "# Code generated by NeuroForge\nprint('Hello, World!')";
}

function downloadNotebook() {
  const editorContent = document.getElementById("editor").value;

  const nb = {
    "cells": [{
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": editorContent.split("\n")
    }],
    "metadata": {},
    "nbformat": 4,
    "nbformat_minor": 5
  };

  const blob = new Blob([JSON.stringify(nb, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "generated_notebook.ipynb";
  a.click();
  URL.revokeObjectURL(url);
}
